# Generated by Django 3.1.1 on 2023-10-02 20:46

from typing import List, Optional

from django.db import migrations, models

import work_in_progress.app.models


class Migration(migrations.Migration):
    initial = True

    dependencies: List[Optional[str]] = []

    operations = [
        migrations.CreateModel(
            name="SystemUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "secret",
                    models.CharField(
                        default=work_in_progress.app.models.get_new_uuid_hex,
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "System User",
                "verbose_name_plural": "System Users",
                "db_table": "system_user",
                "ordering": ["-created_at"],
            },
        ),
    ]
