# Generated by Django 3.1.1 on 2023-10-02 22:22

from django.db import migrations, models
import django.db.models.deletion
import work_in_progress.app.models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_auto_20231002_2119"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="id",
        ),
        migrations.RemoveField(
            model_name="contato",
            name="id",
        ),
        migrations.RemoveField(
            model_name="processo",
            name="id",
        ),
        migrations.AddField(
            model_name="company",
            name="company_id",
            field=models.CharField(
                default=work_in_progress.app.models.get_new_uuid_hex,
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="contato",
            name="contato_id",
            field=models.CharField(
                default=work_in_progress.app.models.get_new_uuid_hex,
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="contato",
            name="criado_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contatos",
                to="app.systemuser",
            ),
        ),
        migrations.AddField(
            model_name="processo",
            name="processo_id",
            field=models.CharField(
                default=work_in_progress.app.models.get_new_uuid_hex,
                editable=False,
                max_length=100,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
