# Generated by Django 3.1.1 on 2023-10-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_auto_20231002_2244"),
    ]

    operations = [
        migrations.AddField(
            model_name="contato",
            name="nome",
            field=models.CharField(
                default="nome", max_length=255, verbose_name="nome do contato"
            ),
        ),
    ]
