# Generated by Django 3.1.1 on 2023-10-14 17:58

import django.db.models.deletion
from django.db import migrations, models

import work_in_progress.app.models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_auto_20231009_1915"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id_produto",
                    models.CharField(
                        default=work_in_progress.app.models.get_new_uuid_hex,
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("descricao", models.CharField(max_length=255)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantidade", models.IntegerField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produtos",
                        to="app.systemuser",
                    ),
                ),
            ],
        ),
    ]
