# Generated by Django 3.1.1 on 2023-10-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_produto"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="nome",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
