services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    logging:
          options:
            max-size: 10m
            max-file: "3"
    volumes:
      - pgdata:/var/lib/postgresql/data
  migrate: 
    build: .
    command:  python3 manage.py migrate
    depends_on:
      - db
    env_file:
      - .env
  back:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - migrate
    ports:
      - 8000:8000
    env_file:
      - .env
  front:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - back
    command: npm start
    restart: 
      unless-stopped
networks:
  app-network:

volumes:
  pgdata:
