name: Python CI

on:
    pull_request:
        branches:
            - master

jobs:
  CI-tests:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install --upgrade pip poetry
        poetry config virtualenvs.create false
        poetry install --no-interaction --no-ansi

    - name: Run Flake8
      run: flake8

    - name: Run MyPy
      run: mypy

    - name: Run Django tests
      env:
        SECRET_KEY: 'changeme'
        PG_HOST: localhost
        PG_USER: postgres
        PG_PASSWORD: postgres
        PG_DATABASE: postgres
        PG_PORT: 5432
      run: |
        python3 manage.py test
